<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ferreteria.Domain\Ferreteria.Domain.csproj" />
    <ProjectReference Include="..\Ferreteria.Shared\Ferreteria.Shared.csproj" />
  </ItemGroup>

</Project>
